name: Deploy to Amazon EC2

on:
#   push:
#     branches: [ "main" ]
  pull_request:
    branches: [ "feat/newDr" ]

permissions:
  contents: read
  
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: ddal-ggak-codedeploy-app
  CODE_DEPLOY_APPLICATION_NAME: codedeploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: codedeploy_g
  ZIP_NAME: zip -r ./finalproject.zip .
  RESOURCE_PATH: ./src/main/resources/application.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
